In [1]:
import numpy as np 

li = []
size = int(input("Enter size of Array : "))

for i in range(size):
    val = int(input(f"Enter value {i+1} : "))
    li.append(val)
arr = np.array(li)
print(arr)

Enter size of Array : 2
Enter value 1 : 12
Enter value 2 : 12
[12 12]


# How to check shape and size of an array?


In [2]:
print(arr.size, arr.shape)

2 (2,)


In [3]:
a = [[1,2,3], [4,5,6], [7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print("Total Shape = ",b.shape)
print("Total Element = ", b.size)

Total Shape =  (3, 3)
Total Element =  9


In [5]:
'''
r1 = [1,2,3]
r2 = [4,5,6]
r3 = [7,8,9]

c1 = [1,4,7]
c2 = [2,5,8]
c3 = [3,6,9]
'''

'\nr1 = [1,2,3]\nr2 = [4,5,6]\nr3 = [7,8,9]\n\nc1 = [1,4,7]\nc2 = [2,5,8]\nc3 = [3,6,9]\n'

In [6]:
#Image ===> pixels ===> (0-255)px ===> 0px (complete black), 255px
#convert ===> grayscale Image ===>
# Image(Pixels) ===> Normalization(0-1) ===> 0px black, 1px white

# 0, 1 ===> Neoron System

#Matrix ===> rows, columns
#Symmetric Matrix ===> n(rows) = n(colemns)
#Asymmetric Matrix ===> n(rows) != n(columns)
#Diagonal Elements = [(1,1), (2,2), (3,3)]


# (1). zeros ===> It will crate an array in which all the elements are zero.

In [7]:
a= np.zeros(4)
a

array([0., 0., 0., 0.])

In [8]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# (2). ones() ===> It will crate an array in which all the elements are one.

In [9]:
a = np.ones(3)
a

array([1., 1., 1.])

In [10]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

# (3). eye() ===> This function will create an array with diagonal values as 1s and rest all are 0s

In [11]:
a = np.eye(3,4) #Asymmetric
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [12]:
a = np.eye(4) #Symmetric  Matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# (4). Diag ==> this function creates a two dimensional array with all the diagonal element as the given value and rest are zeros

In [13]:
import numpy as np
a = np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

# (5). randint ==> this function is used to generate a random number between a given range.

syntax == randint(min_value, max_value, totalnumber)

In [14]:
import numpy as np
a = np.random.randint(1,10,3)
a

array([9, 7, 3])

# (6). This fuinction is used to generate a random number between 0 to 1.

Syntax  == rand(number of values)

In [15]:
import numpy as np
a = np.random.rand(5)
a

array([0.71783564, 0.65475332, 0.80409844, 0.27756062, 0.50217453])

# (7). randn() ==> This function is used to generate a random a number from -3 to 3. This may return postive or negative number as well.

Syntax ==> random.randn(number of values)

In [16]:
import numpy as np
a = np.random.randn(5)
a


array([-1.58530869,  1.55364645, -1.02527904,  0.94734494, -0.93649024])

# Reshpaing data

In [17]:
import numpy as np
a =np.random.randint(0,50,12)
a

array([17,  9, 20, 44, 12, 49, 14, 20, 43, 43, 31, 37])

# n(rows)*n(columns) = n(total_elements)

In [18]:
a.shape

(12,)

In [19]:
a = a.reshape(2,6)
a

array([[17,  9, 20, 44, 12, 49],
       [14, 20, 43, 43, 31, 37]])

In [20]:
a = a.reshape(3,4)
a

array([[17,  9, 20, 44],
       [12, 49, 14, 20],
       [43, 43, 31, 37]])

In [21]:
a = a.reshape(4,3)
a

array([[17,  9, 20],
       [44, 12, 49],
       [14, 20, 43],
       [43, 31, 37]])

In [22]:
a = a.reshape(6,2)
a

array([[17,  9],
       [20, 44],
       [12, 49],
       [14, 20],
       [43, 43],
       [31, 37]])

In [23]:
a = a.reshape(12,1)
a

array([[17],
       [ 9],
       [20],
       [44],
       [12],
       [49],
       [14],
       [20],
       [43],
       [43],
       [31],
       [37]])

# Q : for 64 `

In [24]:
import numpy as np
a =np.random.randint(0,100,64)
a

array([ 2, 97, 87, 58, 34, 45, 14, 75, 70, 78,  7, 71, 43, 93, 32, 75, 72,
       30, 61, 35, 40, 42, 93, 88, 65, 67, 86,  5, 32, 73, 29, 84, 15, 39,
       72, 82, 58,  0, 55, 83, 77, 60, 90, 33, 70, 69,  0, 90, 19, 92, 18,
       82, 98, 51, 71, 89, 60, 89, 35, 78, 52, 24, 11, 56])

In [25]:
a = a.reshape(1,64)
a

array([[ 2, 97, 87, 58, 34, 45, 14, 75, 70, 78,  7, 71, 43, 93, 32, 75,
        72, 30, 61, 35, 40, 42, 93, 88, 65, 67, 86,  5, 32, 73, 29, 84,
        15, 39, 72, 82, 58,  0, 55, 83, 77, 60, 90, 33, 70, 69,  0, 90,
        19, 92, 18, 82, 98, 51, 71, 89, 60, 89, 35, 78, 52, 24, 11, 56]])

In [26]:
a = a.reshape(2,32)
a

array([[ 2, 97, 87, 58, 34, 45, 14, 75, 70, 78,  7, 71, 43, 93, 32, 75,
        72, 30, 61, 35, 40, 42, 93, 88, 65, 67, 86,  5, 32, 73, 29, 84],
       [15, 39, 72, 82, 58,  0, 55, 83, 77, 60, 90, 33, 70, 69,  0, 90,
        19, 92, 18, 82, 98, 51, 71, 89, 60, 89, 35, 78, 52, 24, 11, 56]])

In [27]:
a = a.reshape(4,16)
a

array([[ 2, 97, 87, 58, 34, 45, 14, 75, 70, 78,  7, 71, 43, 93, 32, 75],
       [72, 30, 61, 35, 40, 42, 93, 88, 65, 67, 86,  5, 32, 73, 29, 84],
       [15, 39, 72, 82, 58,  0, 55, 83, 77, 60, 90, 33, 70, 69,  0, 90],
       [19, 92, 18, 82, 98, 51, 71, 89, 60, 89, 35, 78, 52, 24, 11, 56]])

In [28]:
a = a.reshape(8,8)
a

array([[ 2, 97, 87, 58, 34, 45, 14, 75],
       [70, 78,  7, 71, 43, 93, 32, 75],
       [72, 30, 61, 35, 40, 42, 93, 88],
       [65, 67, 86,  5, 32, 73, 29, 84],
       [15, 39, 72, 82, 58,  0, 55, 83],
       [77, 60, 90, 33, 70, 69,  0, 90],
       [19, 92, 18, 82, 98, 51, 71, 89],
       [60, 89, 35, 78, 52, 24, 11, 56]])

In [29]:
a = a.reshape(16,4)
a

array([[ 2, 97, 87, 58],
       [34, 45, 14, 75],
       [70, 78,  7, 71],
       [43, 93, 32, 75],
       [72, 30, 61, 35],
       [40, 42, 93, 88],
       [65, 67, 86,  5],
       [32, 73, 29, 84],
       [15, 39, 72, 82],
       [58,  0, 55, 83],
       [77, 60, 90, 33],
       [70, 69,  0, 90],
       [19, 92, 18, 82],
       [98, 51, 71, 89],
       [60, 89, 35, 78],
       [52, 24, 11, 56]])

In [30]:
a = a.reshape(32,2)
a

array([[ 2, 97],
       [87, 58],
       [34, 45],
       [14, 75],
       [70, 78],
       [ 7, 71],
       [43, 93],
       [32, 75],
       [72, 30],
       [61, 35],
       [40, 42],
       [93, 88],
       [65, 67],
       [86,  5],
       [32, 73],
       [29, 84],
       [15, 39],
       [72, 82],
       [58,  0],
       [55, 83],
       [77, 60],
       [90, 33],
       [70, 69],
       [ 0, 90],
       [19, 92],
       [18, 82],
       [98, 51],
       [71, 89],
       [60, 89],
       [35, 78],
       [52, 24],
       [11, 56]])

In [31]:
a = a.reshape(64,1)
a

array([[ 2],
       [97],
       [87],
       [58],
       [34],
       [45],
       [14],
       [75],
       [70],
       [78],
       [ 7],
       [71],
       [43],
       [93],
       [32],
       [75],
       [72],
       [30],
       [61],
       [35],
       [40],
       [42],
       [93],
       [88],
       [65],
       [67],
       [86],
       [ 5],
       [32],
       [73],
       [29],
       [84],
       [15],
       [39],
       [72],
       [82],
       [58],
       [ 0],
       [55],
       [83],
       [77],
       [60],
       [90],
       [33],
       [70],
       [69],
       [ 0],
       [90],
       [19],
       [92],
       [18],
       [82],
       [98],
       [51],
       [71],
       [89],
       [60],
       [89],
       [35],
       [78],
       [52],
       [24],
       [11],
       [56]])

# Principle of -1

In [33]:
a.reshape(-1,8)

array([[ 2, 97, 87, 58, 34, 45, 14, 75],
       [70, 78,  7, 71, 43, 93, 32, 75],
       [72, 30, 61, 35, 40, 42, 93, 88],
       [65, 67, 86,  5, 32, 73, 29, 84],
       [15, 39, 72, 82, 58,  0, 55, 83],
       [77, 60, 90, 33, 70, 69,  0, 90],
       [19, 92, 18, 82, 98, 51, 71, 89],
       [60, 89, 35, 78, 52, 24, 11, 56]])

# seed function() ==> We know that randint function generates random numbers. Everytime we run the program, new set of random number is genrated. So, solve this problem we will use seed function.


In [74]:
import numpy as np
a= np.random.randint(1,100,10)
np.random.seed(1)
a

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

## View vs Copy ==> When we slice a sub-array from an array, It may be done by two ways.


## View

In [75]:
import numpy as np
a = np.array([12,12,53,23,24,13,4,32])
b = a[3:5]
b[:] = 0
a

array([12, 12, 53,  0,  0, 13,  4, 32])

## Copy

In [76]:
a = np.array([12,12,53,23,24,13,4,32])
b = a[3:5].copy()
b[:] = 0
a

array([12, 12, 53, 23, 24, 13,  4, 32])

## conditional selection

In [77]:
import numpy as np
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [78]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [79]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [80]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [81]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

## Operations on Array

In [82]:
import numpy as np
a = np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [83]:
a+2

array([3, 4, 5, 6])

In [84]:
a**2

array([ 1,  4,  9, 16])

In [85]:
a = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [86]:
b = np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [87]:
a+b

array([[ 6,  8],
       [10, 12]])

In [88]:
b-a

array([[4, 4],
       [4, 4]])

In [89]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [90]:
b*a

array([[ 5, 12],
       [21, 32]])

In [91]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [92]:
import numpy as np
a = np.array([10,20,30,40,50])
np.min(a)

10

In [93]:
np.max(a)

50

In [94]:
np.argmin(a)

0

In [95]:
np.argmax(a)

4

In [96]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [97]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

## Linspace() ==> This function returns value between a given range and with a same gap between consecutive elements.


In [108]:
import numpy as np
a= np.linspace(1,20,5)
a


array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

## np.unique(arr,return_index = True, return_count = True)

returns 3 array ==> 1.the array contain unique values. 2. The array with respective index values. 3. The array with counting of frequency of each element.

In [112]:
a = np.array([10,20,30,90,68,90,40,50])
np.unique(a,True,True)

(array([10, 20, 30, 40, 50, 68, 90]),
 array([0, 1, 2, 6, 7, 4, 3], dtype=int64),
 array([0, 1, 2, 6, 5, 6, 3, 4], dtype=int64))

## Horizontal and verticle stacking

In [113]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [114]:
b

array([5, 6, 7, 8])

In [115]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [116]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])